FROM --platform=linux/arm64 alpine:latest as base

WORKDIR /app

RUN apk --no-cache add ca-certificates curl && \
    curl -LO "https://get.helm.sh/helm-v3.13.0-linux-arm64.tar.gz" && \
    tar -zxvf helm-v3.13.0-linux-arm64.tar.gz && \
    mv linux-arm64/helm /usr/local/bin/helm && \
    rm -rf linux-arm64 helm-v3.13.0-linux-arm64.tar.gz && \
    chmod +x /usr/local/bin/helm

COPY ./drone-helm /app/

CMD ["/app/drone-helm"]