FROM --platform=linux/amd64 alpine:latest as base

WORKDIR /app

RUN apk --no-cache add ca-certificates curl && \
    curl -LO "https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz" && \
    tar -zxvf helm-v3.8.0-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    rm -rf linux-amd64 helm-v3.8.0-linux-amd64.tar.gz && \
    chmod +x /usr/local/bin/helm

COPY ./drone-helm /app/

CMD ["/app/drone-helm"]