FROM --platform=amd64 alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates curl && \
    curl -LO "https://get.helm.sh/helm-v3.13.0-linux-amd64.tar.gz" && \
    tar -zxvf helm-v3.13.0-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm && \
    rm -rf linux-amd64 helm-v3.13.0-linux-amd64.tar.gz && \
    chmod +x /usr/local/bin/helm

ADD ./drone-helm /app/

ENTRYPOINT ["/app/drone-helm"]